HiTours.Web/Areas/Admin/Controllers/CancellationPolicyController.cs
// <copyright file="CancellationPolicyController.cs" company="Luxury Travel Deals">
// Copyright (c) Luxury Travel Deals All rights reserved.
// </copyright>

namespace HiTours.Web.Areas.Admin.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using AutoMapper;
    using HiTours.Core;
    using HiTours.Data.DataBase.Model;
    using HiTours.Models;
    using HiTours.Services;
    using HiTours.ViewModels;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.Configuration;

    /// <summary>
    /// CityController
    /// </summary>
    /// <seealso cref="HiTours.Web.AdminController" />
    public class CancellationPolicyController : AdminController
    {
        private readonly IHotelierService hotelierServices;

        /// <summary>
        /// The master service
        /// </summary>
        private readonly IMasterService masterService;
        private readonly IVendorService vendorService;
        private readonly ICancellationService cancellationService;
        private readonly IHostingEnvironment hostingEnvironment;

        /// <summary>
        /// Initializes a new instance of the <see cref="CancellationPolicyController" /> class.
        /// </summary>
        /// <param name="configuration">Configuration</param>
        /// <param name="cancellationService">Cancellation Service</param>
        /// <param name="hostingEnvironment">Hosting Enviorment</param>
        /// <param name="mapper">The mapper.</param>
        /// <param name="hotel">Type of the hoteroom.</param>
        /// <param name="masterService">The master service.</param>
        /// <param name="vendorService">Vendor Service</param>
        public CancellationPolicyController(IConfiguration configuration, ICancellationService cancellationService, IHostingEnvironment hostingEnvironment, IMapper mapper, IHotelierService hotel, IMasterService masterService, IVendorService vendorService)
            : base(mapper, configuration)
        {
            this.cancellationService = cancellationService;
            this.hostingEnvironment = hostingEnvironment;
            this.vendorService = vendorService;
            this.hotelierServices = hotel;
            this.masterService = masterService;
        }

        /// <summary>
        /// Indexes the specified model.
        /// </summary>
        /// <returns>DataTable Pagging</returns>
        /// <param name="dealType">Deal Type</param>
        public IActionResult Index(int? dealType)
        {
            CancellationPolicyViewModel model = new CancellationPolicyViewModel
            {
                Id = 0,
                DealType = dealType != null && dealType != 0 ? dealType : 0
            };
            return this.View(model);
        }

        /// <summary>
        /// Indexes the specified model.
        /// </summary>
        /// <returns>DataTable Pagging</returns>
        /// <param name="dealType">Deal Type</param>
        public async Task<IActionResult> GetCancellationPolicyByDealType(int dealType)
        {
            List<CancellationPolicyViewModel> model = await this.cancellationService.GetCancellationPolicyByDealType(dealType);
            foreach (var item in model)
            {
                item.MarginTypeItems = (await this.cancellationService.GetMarginTypeItems()).ToSelectList();
            }

            this.ViewBag.DealType = dealType;
            return this.PartialView("_CancellationPolicy", model);
        }

        /// <summary>
        /// Indexes the specified model.
        /// </summary>
        /// <returns>DataTable Pagging</returns>
        /// <param name="dealType">Deal Type</param>
        public async Task<IActionResult> AddCancellationPolicyRow(int dealType)
        {
            CancellationPolicyViewModel model = new CancellationPolicyViewModel
            {
                Id = 0,
                IsDeleted = false,
                DealType = dealType,
                MarginTypeItems = (await this.cancellationService.GetMarginTypeItems()).ToSelectList()
            };
            this.ViewBag.DealType = dealType;
            return this.PartialView("_CancellationPolicyRow", model);
        }

        /// <summary>
        /// Indexes the specified model.
        /// </summary>
        /// <returns>DataTable Pagging</returns>
        /// <param name="model">Model</param>
        public async Task<IActionResult> AddCancellationPolicies(List<CancellationPolicyViewModel> model)
        {
            if (this.ModelState.IsValid)
            {
                if (model.Count > 0)
                {
                    int dealTypeId = Convert.ToInt32(model[0].DealType);
                    foreach (var item in model)
                    {
                        if (item.IsDeleted)
                        {
                            if (item.Id > 0)
                            {
                                var record = await this.cancellationService.GetCancellationPolicyById(item.Id);
                                record.IsDeleted = true;
                                await this.cancellationService.UpdateCancellationPolicy(record);
                            }
                        }
                        else if (item.Id > 0)
                        {
                            ////Update
                            var record = this.Mapper.Map<CancellationPolicyModel>(item);
                            record.UpdateAuditInfo(new Guid(this.HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Sid).Value));
                            await this.cancellationService.UpdateCancellationPolicy(record);
                        }
                        else
                        {
                            var record = this.Mapper.Map<CancellationPolicyModel>(item);
                            record.IsActive = true;
                            record.SetAuditInfo(new Guid(this.HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Sid).Value));
                            await this.cancellationService.AddCancellationPolicy(record);
                        }
                    }

                    this.ShowMessage("Successfully Updated", Enums.MessageType.Success);
                    return this.RedirectToAction("Index", new { @dealType= dealTypeId });
                }
            }

            return this.RedirectToAction("Index");
        }
    }
}

HiTours.Web/Areas/Admin/Views/CancellationPolicy/Index.cshtml
@model CancellationPolicyViewModel;
@{
    ViewData["Title"] = "Cancellation Policy";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="box no-top-border">
    <div class="box-header with-border">
        <h3 class="box-title"><span><i class='fa fa-fw fa-ban'></i> @this.ViewBag.Title</span></h3>
    </div>
    <div class="box-body">
        <div class="form-group col-md-4">
            <label asp-for="DealType"></label>
            <select select2-stop-render="true" asp-for="DealType" class="form-control" id="dealTypeSelect" select2-Placeholder="Select Deal Type">
                <option value="0">--Select Deal Type--</option>
                <option value="1">Hotel</option>
                <option value="2">Tour</option>
                <option value="3">Cruise</option>
                <option value="5">Bus</option>
                <option value="4">Flights</option>
            </select>
            <span class="loader" style="display:none;"><i class="fa fa-fw fa-spin fa-spinner"></i></span>
        </div>
        <div class="cancelltion_policy_section">

        </div>
    </div>
</div>
@section scripts{
    <script>
        var $section = $('.cancelltion_policy_section');
        var $loader = $('.loader');
        
        $(document).on('change', '#dealTypeSelect', function (e) {
            $loader.show();
            if ($(this).val() != 0) {
                $.get('@Url.Action("GetCancellationPolicyByDealType", "CancellationPolicy", new { @area="Admin"})', { 'dealType': $('#dealTypeSelect').val() }, function (result)
                {
                    $('.cancelltion_policy_section').html(result);
                    initSelect2();
                    $loader.hide();
                    BindValidation();
                });
                
            }
            else {
                $section.html('');
            }
        });
        $(document).on('click', '.add_button', function (e) {
            $.get('@Url.Action("AddCancellationPolicyRow", "CancellationPolicy", new { @area="Admin"})', { 'dealType': $('#dealTypeSelect').val() }, function (result)
            {
                $("#formCancellationPolicy table tbody").append(result);
                initSelect2();
                BindValidation()
            });
        });
        $(document).on('click', '.delete-item-row', function (e) { 
            var row = $(this).closest('tr');
            $(row).find('.delete_row').val(true);
            $(row).hide();
        })
        function BindValidation() {
            var form = $('#formCancellationPolicy');
            form.removeData('validator');
            form.removeData('unobtrusiveValidation');
            $.validator.unobtrusive.parse(form);
        }
        $(docuent).ready(function (e) {
            $('#dealTypeSelect').trigger('change');
        })
        
    </script>
}

HiTours.Web/Areas/Admin/Views/CancellationPolicy/_CancellationPolicy.cshtml
@model List<CancellationPolicyViewModel>;

<form asp-antiforgery="true" id="formCancellationPolicy" action="@Url.Action("AddCancellationPolicies", "CancellationPolicy")" method="post" enctype="multipart/form-data">
    <input type="hidden" name="DealTypeIdentifier" value="@this.ViewBag.DealType" />
    <div class="col-sm-12 col-xs-12">
        <div class="form-group">
            <div class="tax-tabel-wrap">
                <div class="table-responsive">
                    <table id="tpimages" class="table table-standard table-bordered invoice-tabel-2">
                        <thead>
                            <tr>
                                <th>From Days</th>
                                <th>To Days</th>
                                <th style="width:200px;">Deduction Type</th>
                                <th>Deduction Charge</th>
                                <th><i class="fa fa-trash-o"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (this.Model != null && this.Model.Count > 0)
                            {
                                @foreach (var file in Model)
                                {
                                    @this.Html.Partial("_CancellationPolicyRow", file)
                                }
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="6" style="text-align:right"><a href="javascript:void(0);" data-addpackageimage="true" title="Add Booking Date" class="btn btn-primary add_button">+ Add Policy</a></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @this.Html.ButtonBottom(new[] { new Button(Enums.ButtonType.SaveandReload)})
    @*@this.Html.ButtonBottom(new[] { new Button(Enums.ButtonType.SaveandReload) })*@
</form>

HiTours.Web/Areas/Admin/Views/CancellationPolicy/_CancellationPolicyRow.cshtml
@model CancellationPolicyViewModel;
@using HtmlHelpers.BeginCollectionItemCore
<tr>
    @using (this.Html.BeginCollectionItem("model"))
    {
        <td>
            <div class="field-col">
                <input class="form-control" asp-for="MinDay" type="number" placeholder="From Days" />
                <span asp-validation-for="MinDay"></span>
            </div>

        </td>
        <td>
            <div class="field-col">
                <input class="form-control" asp-for="MaxDay" type="number" placeholder="To Days" />
                <span asp-validation-for="MaxDay"></span>
            </div>
        </td>
        <td>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="IsActive" />
            <input type="hidden" asp-for="UpdatedBy" />
            <input type="hidden" asp-for="UpdatedDate" />
            <input type="hidden" asp-for="CreatedBy" />
            <input type="hidden" asp-for="CreatedDate" />
            <input type="hidden" asp-for="IsDeleted" class="delete_row" />
            <input type="hidden" asp-for="DealType" />
            <div class="field-col">
                <select asp-for="ChargeType" selected="@Model.ChargeType" class="form-control" id="ChargeType" select2-Placeholder="Deduction Type" asp-items="Model.MarginTypeItems"
                        select2-value="@Model.ChargeType"></select>
                <span asp-validation-for="ChargeType"></span>
            </div>
        </td>
        <td>
            <div class="field-col">
                <input class="form-control" asp-for="Charge" placeholder="Deduction Charge" />
                <span asp-validation-for="Charge"></span>
            </div>
        </td>
        <td valign="middle" class="city-delete-row-box">
            <a class="delete-item-row" href="javaScript:void(0)"><i class="fa fa-trash-o"></i></a>
        </td>
    }
</tr>